server:
  port: 8083
spring:
  application:
    name: scoring-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/risk_assessment
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: INFO
    com.riskassessment.scoring: DEBUG
