server:
  port: 9006

spring:
  application:
    name: alert-service
  datasource:
    url: jdbc:postgresql://localhost:5432/risk_alert_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025 # MailHog or similar default
    username: user
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/